Lesson11 comments
supervoron1/qna-rails pull request #5
Opened 2022-12-22 16:53 UTC by supervoron1

2022-12-22 18:29 UTC, russo-matrosso commented on app/channels/answers_channel.rb
> +    stream_from "answers"
Получается что все ответы в один канал? Даже если ты вообще на другом вопросе? Неправильно как-то
Чтоит сюда еще передавать id вопроса

2022-12-22 18:29 UTC, russo-matrosso commented on app/channels/answers_channel.rb
> +end
Рубокоп, пожалуйста

2022-12-22 18:29 UTC, russo-matrosso commented on app/controllers/application_controller.rb
> +    # -1 value for non-auth users
Не понял зачем это. То есть будет id другого юзера? Это как? Может, просто передавать что нет current_user и от этого отталкиваться?

2022-12-23 10:27 UTC, vkurennov requested changes

2022-12-23 10:27 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    ActionCable.server.broadcast "answers/#{@answer.question_id}", answer: @answer.body, user_id: @answer.user_id
лучше отправлять весь объект ответа целиком, а не отдельными полями

2022-12-23 10:27 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +module Commented
это ложится в отдельный ресурс со своим контроллером

2022-12-23 10:27 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +      comment: @comment.body,
нет смысла по отдельным полям разбивать, достаточно передать `comment: @comment`

2022-12-23 10:27 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +                                 ApplicationController.render(
если передаешь json, то ApplicationController.render не нужен

2023-01-22 17:23 UTC, merged